services:
  - type: worker
    name: music-telegram-bot
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    # بسیار مهم: برای جلوگیری از خطای Conflict حتما باید 1 باشد
    numInstances: 1
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: MUSIXMATCH_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:////app/data/music_bot.db
      - key: DEFAULT_TIMEZONE
        value: Asia/Tehran
      - key: PYTHONUNBUFFERED
        value: "1"
    # اتصال دیسک دائمی برای دیتابیس (تا با ریستارت پاک نشود)
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1