services:
  - type: worker
    name: music-telegram-bot
    env: docker  # تغییر از python به docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: MUSIXMATCH_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///data/music_bot.db
      - key: DEFAULT_TIMEZONE
        value: Asia/Tehran
    # برای ذخیره‌سازی دیتابیس (اختیاری)
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1